# Generated by Django 3.1.4 on 2020-12-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('bname', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'boat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sailor',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sailor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('sid', models.OneToOneField(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sailor.sailor')),
                ('day', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'reserve',
                'managed': False,
            },
        ),
    ]
