# Generated by Django 3.1.4 on 2021-01-05 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('ad_id', models.IntegerField(db_column='Ad_id', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=9, null=True)),
                ('description', models.CharField(db_column='Description', max_length=800)),
                ('status', models.CharField(db_column='Status', max_length=30)),
                ('expiry_date', models.DateField(db_column='Expiry_Date')),
                ('area', models.CharField(db_column='Area', max_length=30)),
                ('country', models.CharField(db_column='Country', max_length=30)),
                ('state', models.CharField(db_column='State', max_length=30)),
                ('city', models.CharField(db_column='City', max_length=30)),
                ('price', models.IntegerField(db_column='Price')),
            ],
            options={
                'db_table': 'advertisement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HiringAdvertisement',
            fields=[
                ('h_id', models.IntegerField(db_column='H_id', primary_key=True, serialize=False)),
                ('qualification', models.CharField(db_column='Qualification', max_length=30)),
                ('experience', models.CharField(blank=True, db_column='Experience', max_length=500, null=True)),
                ('task', models.CharField(db_column='Task', max_length=300)),
                ('type', models.CharField(db_column='Type', max_length=30)),
                ('salary', models.IntegerField(db_column='Salary')),
                ('working_hours', models.IntegerField(db_column='Working_Hours')),
            ],
            options={
                'db_table': 'hiring_advertisement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('newsletter_email', models.CharField(db_column='Newsletter_Email', max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'news_letter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyCompany',
            fields=[
                ('company_name', models.CharField(db_column='Company_Name', max_length=30, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=50, null=True, unique=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=30, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'property_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyCompanyContact',
            fields=[
                ('contact_no', models.IntegerField(db_column='Contact_No', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'property_company_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(db_column='Email', max_length=30)),
                ('name', models.CharField(db_column='Name', max_length=30, primary_key=True, serialize=False)),
                ('contact_no', models.IntegerField(db_column='Contact_No', unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Boat',
        ),
        migrations.CreateModel(
            name='HouseOrApartmentAdvertisement',
            fields=[
                ('type', models.CharField(blank=True, db_column='Type', max_length=9, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('no_of_bedrooms', models.IntegerField(db_column='No_of_bedrooms')),
                ('no_of_bathrooms', models.IntegerField(db_column='No_of_bathrooms')),
                ('floor_number', models.IntegerField(db_column='Floor_number')),
                ('ad', models.OneToOneField(db_column='Ad_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sailor.advertisement')),
            ],
            options={
                'db_table': 'house_or_apartment_advertisement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlotAdvertisement',
            fields=[
                ('image', models.TextField(blank=True, null=True)),
                ('ad', models.OneToOneField(db_column='Ad_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sailor.advertisement')),
                ('neighborhood', models.CharField(blank=True, db_column='Neighborhood', max_length=100, null=True)),
            ],
            options={
                'db_table': 'plot_advertisement',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
        migrations.DeleteModel(
            name='Sailor',
        ),
    ]
