# Generated by Django 3.1.4 on 2021-01-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'managed': True},
        ),
    ]
