# Generated by Django 3.1.4 on 2021-01-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0005_auto_20210116_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'managed': False},
        ),
    ]
