# Generated by Django 3.1.4 on 2021-01-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0006_auto_20210119_0308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
