# Generated by Django 3.1.4 on 2021-02-01 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0007_delete_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementImages',
            fields=[
                ('images', models.ImageField(blank=True, null=True, upload_to='media')),
                ('id', models.OneToOneField(db_column='Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sailor.advertisement')),
            ],
            options={
                'db_table': 'advertisement_images',
                'managed': False,
            },
        ),
    ]
