# Generated by Django 3.1.4 on 2021-02-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0008_advertisementimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisementImages',
        ),
    ]
